title: kyhoon001
subtitle: kyhoon001
description: Portfolio Test

author: 김영훈
email: kyhoon001@naver.com
avatar: assets/images/avatar.jpg

baseurl: ""
url: "https://kyhoon001.github.io"

# Social settings
facebook_url: ""
github_url: https://github.com/kyhoon001
linkedin_url: ""

# SEO settiongs
google_analytics: UA-112211352-1

# Build settings
remote_theme: chrisbobbe/jekyll-theme-prologue
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Necessary for Prologue theme:
collections: [sections]
